-- Tenant-scoped Razorpay credentials. API and webhook secrets are AES-256-GCM ciphertexts
-- generated by the application; CREDENTIAL_ENCRYPTION_KEY never enters this database.
alter table public.restaurants
  add column if not exists razorpay_key_id text,
  add column if not exists razorpay_key_secret text,
  add column if not exists razorpay_webhook_secret text;

alter table public.orders
  add column if not exists razorpay_key_id_snapshot text,
  add column if not exists razorpay_key_secret_snapshot text,
  add column if not exists razorpay_webhook_secret_snapshot text;

alter table public.razorpay_webhook_events
  add column if not exists restaurant_id uuid references public.restaurants(id) on delete set null;

create or replace function public.block_direct_razorpay_credential_updates()
returns trigger language plpgsql as $$
begin
  if auth.role() <> 'service_role'
    and (new.razorpay_key_id is distinct from old.razorpay_key_id
      or new.razorpay_key_secret is distinct from old.razorpay_key_secret
      or new.razorpay_webhook_secret is distinct from old.razorpay_webhook_secret) then
    raise exception 'Razorpay credentials can only be updated by the trusted server';
  end if;
  return new;
end;
$$;

drop trigger if exists restaurants_block_direct_razorpay_credentials on public.restaurants;
create trigger restaurants_block_direct_razorpay_credentials
before update of razorpay_key_id, razorpay_key_secret, razorpay_webhook_secret on public.restaurants
for each row execute procedure public.block_direct_razorpay_credential_updates();

-- Ciphertexts remain safe if selected under row-level access; plaintext is never persisted.
comment on column public.restaurants.razorpay_key_secret is 'AES-256-GCM ciphertext; write only through the trusted server.';
comment on column public.restaurants.razorpay_webhook_secret is 'AES-256-GCM ciphertext; write only through the trusted server.';
